### ISSUE TITLE
Error: README.md in lib.rs while vendoring

### ISSUE THREAD

**Issue by mplsgrant** [DioxusLabs/taffy#228] opened 2022-09-13 14:32 UTC
## `taffy` version

taffy = "0.1.0"

## Platform

Rust, debian linux

## What you did

I tried to vendor my sources.

1. `git clone https://github.com/mplsgrant/taproot-bevy-taffy-error.git`
2. `cd taproot-bevy-taffy-error/`
3. `mkdir vendor`
4. `cargo vendor vendor`
5.  `vim .cargo/config.toml`

Uncomment at the bottom of *.cargo/config.toml*: 

```
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
```
6. `cargo build`

## What went wrong

I got the following error: 

	error: couldn't read /home/user/taproot-bevy-taffy-error/vendor/taffy/src/../README.md: No such file or directory (os error 2)
	--> /home/user/taproot-bevy-taffy-error/vendor/taffy/src/lib.rs:1:10
	|
	1 | #![doc = include_str!("../README.md")]
	|          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	|
	= note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

	error: could not compile `taffy` due to previous error

**Comment by TimJentzsch** [comment] 2022-09-13 14:59
I think this is a duplicate of #217 and fixed by #219.
We probably just need to publish a new release with the changes.

**Closed** 2022-11-23 22:27 UTC
Labels: bug, duplicate, meta
