### ISSUE TITLE
`Undefined` and `Auto` should not have equivalent behavior

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#347] opened 2023-02-03 01:05 UTC
## `taffy` version

0.3

## Context

              Undefined and Auto definitely aren't the same. 

Ultra minimal example, red window:
```rust
use bevy::prelude::*;
fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(|mut commands: Commands| {
            commands.spawn(Camera2dBundle::default());
            commands.spawn(NodeBundle {
                style: Style {
                    size: Size::new(Val::Percent(100.), Val::Auto),
                    ..Default::default()
                },
                background_color: BackgroundColor(Color::RED),
                ..Default::default()
            });
        })
        .run();
}
```

Grey  window:
```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_startup_system(|mut commands: Commands| {
            commands.spawn(Camera2dBundle::default());
            commands.spawn(NodeBundle {
                style: Style {
                    size: Size::new(Val::Percent(100.), Val::Undefined),
                    ..Default::default()
                },
                background_color: BackgroundColor(Color::RED),
                ..Default::default()
            });
        })
        .run();
```

The Taffy 2.x compute source is full of predicates like ```child_style.cross_size(constants.dir) == Dimension::Auto``` etc.

_Originally posted by @ickshonpe in https://github.com/bevyengine/bevy/issues/7475#issuecomment-1414135140_

**Comment by nicoburns** [comment] 2023-02-03 01:21
I believe that `Undefined` and `Auto` *should* have equivalent behaviour (see https://developer.mozilla.org/en-US/docs/Web/CSS/width#formal_definition which says that the "initial" (i.e. default) value if `width` is `auto`). As I understand it, the problem is that in Taffy 0.2, `Undefined` and `Auto` do not have equivalent behaviour (although it's quite close). I believe this is already fixed in Taffy 0.3 by https://github.com/DioxusLabs/taffy/pull/269 which removed `Dimension::Undefined` entirely. Although I may have caused some confusion on the bevy issues because I thought that PR was already included in Taffy 0.2 and it turns out it isn't.

**Closed** 2023-02-03 02:56 UTC
Labels: bug
