### ISSUE TITLE
Taffy 0.3.18 crashes rustdoc build 

### ISSUE THREAD

**Issue by mintlu8** [DioxusLabs/taffy#644] opened 2024-04-12 12:44 UTC
## `taffy` version

0.3.18

## Platform

Rustdoc

## What you did

Compiling `bevy_ui` on rustdoc

## What went wrong

<img width="1001" alt="taffy" src="https://github.com/DioxusLabs/taffy/assets/139340600/456e5dc6-b3f8-4b7c-82aa-ffdae4e73d46">

**Comment by xangelix** [comment] 2024-04-12 15:29
Builds on nightly seem broken with this.

**Comment by djeedai** [comment] 2024-04-12 19:58
I'm on osx stable and same issue.

**Comment by djeedai** [comment] 2024-04-12 20:21
I've tried 0.3.10 (min version for Bevy) to 0.3.18 and they all fail the same. But I don't see any other Bevy project compiling so it really looks like all those versions are broken?

**Comment by djeedai** [comment] 2024-04-12 20:45
Duplicate of #642 ?

**Comment by nicoburns** [comment] 2024-04-12 22:40
This is caused by https://github.com/rust-lang/rust/issues/123824 For future reference, the following version exhibits the issue when compiling Taffy 0.3.18: rustc 1.79.0-nightly (a07f3eb43 2024-04-11)

@djeedai Are you sure you're seeing this on stable Rust. I am unable to reproduce this on rust 1.77.0 or 1.77.2 on macOS (but I am seeing the failure on

**Comment by nicoburns** [comment] 2024-04-12 22:41
I've published Taffy 0.3.19 which fixes the internal failure within Taffy. Although 3rd-party callers of Taffy's APIs may need to update their calls.

**Closed by nicoburns** 2024-04-12 22:41 UTC
Labels: bug

**Comment by djeedai** [comment] 2024-04-13 07:47
No this was in nightly my bad. The project I was trying had a forced nightly in a config file, and hadn't realized. This builds with stable.
